<a href="https://colab.research.google.com/github/wil28/AnalysisMultivariate/blob/main/Multivariate_using_LDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import accuracy_score

In [ ]:
# Data preparation
data = {
    'Group': ['MEMORY', 'MEMORY', 'MEMORY', 'PERCEPTION', 'PERCEPTION', 'PERCEPTION', 'COMMUNICATION', 'COMMUNICATION', 'COMMUNICATION'],
    'PERF': [87, 97, 112, 102, 85, 76, 120, 85, 99],
    'INFO': [5, 7, 9, 16, 10, 9, 12, 8, 9],
    'VERBEXP': [31, 36, 42, 45, 38, 32, 30, 28, 27],
    'AGE': [6.4, 8.3, 7.2, 7.0, 7.6, 6.2, 8.4, 6.3, 8.2]
}

df = pd.DataFrame(data)

# Separating features and target
X = df[['PERF', 'INFO', 'VERBEXP', 'AGE']]
y = df['Group']

# Initialize LDA
lda = LDA()

# Fit the model
lda.fit(X, y)

# Get the coefficients
coefficients = lda.coef_
intercept = lda.intercept_

# Display the results
coefficients, intercept

coefficients, intercept

(array([[ 0.07326369,  1.69581   , -1.23902872, -0.06067268],
        [ 0.63194641, -5.27940623,  1.33404635, -1.98479705],
        [-0.7052101 ,  3.58359623, -0.09501763,  2.04546973]]),
 array([ 14.74795271, -51.82281562,  14.70389873]))

In [ ]:
coefficients


array([[ 0.07326369,  1.69581   , -1.23902872, -0.06067268],
       [ 0.63194641, -5.27940623,  1.33404635, -1.98479705],
       [-0.7052101 ,  3.58359623, -0.09501763,  2.04546973]])

In [ ]:
intercept

array([ 14.74795271, -51.82281562,  14.70389873])

In [ ]:
prior_probabilities = lda.priors_
prior_probabilities

array([0.33333333, 0.33333333, 0.33333333])

In [ ]:
# Fungsi untuk menghitung nilai diskriminan
def diskriminan_fungsi(x, coef, intercept):
    return np.dot(x, coef) + intercept

In [ ]:
data_1 = np.array([[87, 5, 31, 6.4]])

In [ ]:
data_1.shape

(1, 4)

In [ ]:
# Menghitung nilai diskriminan untuk setiap kelompok
D1 = diskriminan_fungsi(data_1, coefficients[0], intercept[0])
D2 = diskriminan_fungsi(data_1, coefficients[1], intercept[1])
D3 = diskriminan_fungsi(data_1, coefficients[2], intercept[2])

In [ ]:
# Menampilkan hasil
print("Nilai Diskriminan untuk MEMORY (D1):", D1)
print("Nilai Diskriminan untuk PERCEPTION (D2):", D2)
print("Nilai Diskriminan untuk COMMUNICATION (D3):", D3)

Nilai Diskriminan untuk MEMORY (D1): [-9.19725176]
Nilai Diskriminan untuk PERCEPTION (D2): [5.41222624]
Nilai Diskriminan untuk COMMUNICATION (D3): [-18.58593867]


In [ ]:
# Menentukan klasifikasi
nilai_diskriminan = [D1, D2, D3]
kelompok = ['MEMORY', 'PERCEPTION', 'COMMUNICATION']
klasifikasi = kelompok[np.argmax(nilai_diskriminan)]
print("Klasifikasi: ", klasifikasi)

Klasifikasi:  PERCEPTION


In [ ]:
data

{'Group': ['MEMORY',
  'MEMORY',
  'MEMORY',
  'PERCEPTION',
  'PERCEPTION',
  'PERCEPTION',
  'COMMUNICATION',
  'COMMUNICATION',
  'COMMUNICATION'],
 'PERF': [87, 97, 112, 102, 85, 76, 120, 85, 99],
 'INFO': [5, 7, 9, 16, 10, 9, 12, 8, 9],
 'VERBEXP': [31, 36, 42, 45, 38, 32, 30, 28, 27],
 'AGE': [6.4, 8.3, 7.2, 7.0, 7.6, 6.2, 8.4, 6.3, 8.2]}

In [ ]:

# Data baru yang akan diklasifikasikan
data_baru = np.array([
    [87, 5, 31, 6.4],
    [97, 7, 36, 8.3],
    [112, 9, 42, 7.2],
    [102, 16, 45, 7.0],
    [85, 10, 38, 7.6],
    [76, 9, 32, 6.2],
    [120, 12, 30, 8.4],
    [85, 8, 28, 6.3],
    [99, 9, 27, 8.2]
])


# Menghitung nilai diskriminan untuk setiap kelompok
D1 = diskriminan_fungsi(data_baru, coefficients[0], intercept[0])
D2 = diskriminan_fungsi(data_baru, coefficients[1], intercept[1])
D3 = diskriminan_fungsi(data_baru, coefficients[2], intercept[2])

# Menentukan klasifikasi untuk setiap data
kelompok = ['MEMORY', 'PERCEPTION', 'COMMUNICATION']
klasifikasi = [kelompok[np.argmax([d1, d2, d3])] for d1, d2, d3 in zip(D1, D2, D3)]

# Data asli dengan label yang benar
label_asli = ['MEMORY', 'MEMORY', 'MEMORY', 'PERCEPTION', 'PERCEPTION', 'PERCEPTION', 'COMMUNICATION', 'COMMUNICATION', 'COMMUNICATION']

# Menghitung akurasi
akurasi = accuracy_score(label_asli, klasifikasi)
print("Akurasi klasifikasi: {:.2f}%".format(akurasi * 100))

# Menampilkan hasil klasifikasi
for i, k in enumerate(klasifikasi):
    print(f"Data {i+1} diklasifikasikan ke dalam kelompok: {k}")


Akurasi klasifikasi: 0.00%
Data 1 diklasifikasikan ke dalam kelompok: PERCEPTION
Data 2 diklasifikasikan ke dalam kelompok: PERCEPTION
Data 3 diklasifikasikan ke dalam kelompok: PERCEPTION
Data 4 diklasifikasikan ke dalam kelompok: COMMUNICATION
Data 5 diklasifikasikan ke dalam kelompok: COMMUNICATION
Data 6 diklasifikasikan ke dalam kelompok: COMMUNICATION
Data 7 diklasifikasikan ke dalam kelompok: MEMORY
Data 8 diklasifikasikan ke dalam kelompok: MEMORY
Data 9 diklasifikasikan ke dalam kelompok: MEMORY


# Sesuai buku tabhanic

In [ ]:
import numpy as np
import pandas as pd

# Data preparation
data = {
    'Group': ['MEMORY', 'MEMORY', 'MEMORY', 'PERCEPTION', 'PERCEPTION', 'PERCEPTION', 'COMMUNICATION', 'COMMUNICATION', 'COMMUNICATION'],
    'PERF': [87, 97, 112, 102, 85, 76, 120, 85, 99],
    'INFO': [5, 7, 9, 16, 10, 9, 12, 8, 9],
    'VERBEXP': [31, 36, 42, 45, 38, 32, 30, 28, 27],
    'AGE': [6.4, 8.3, 7.2, 7.0, 7.6, 6.2, 8.4, 6.3, 8.2]
}

df = pd.DataFrame(data)

# Memisahkan fitur dan target
X = df[['PERF', 'INFO', 'VERBEXP', 'AGE']].values
y = df['Group'].values

# Hitung rata-rata untuk setiap kelompok
mean_vectors = []
groups = np.unique(y)
for group in groups:
    mean_vectors.append(np.mean(X[y == group], axis=0))

# Hitung rata-rata keseluruhan
overall_mean = np.mean(X, axis=0)

# Hitung Swg (dalam kelompok)
Swg = np.zeros((X.shape[1], X.shape[1]))
for group, mean_vec in zip(groups, mean_vectors):
    group_scatter = np.zeros((X.shape[1], X.shape[1]))
    for row in X[y == group]:
        row, mean_vec = row.reshape(X.shape[1], 1), mean_vec.reshape(X.shape[1], 1)
        group_scatter += (row - mean_vec).dot((row - mean_vec).T)
    Swg += group_scatter

# Hitung Sbg (antara kelompok)
Sbg = np.zeros((X.shape[1], X.shape[1]))
for mean_vec in mean_vectors:
    mean_vec = mean_vec.reshape(X.shape[1], 1)
    overall_mean = overall_mean.reshape(X.shape[1], 1)
    n = X[y == group].shape[0]
    Sbg += n * (mean_vec - overall_mean).dot((mean_vec - overall_mean).T)

Swg, Sbg


(array([[1286.        ,  220.        ,  348.33333333,   50.        ],
        [ 220.        ,   45.33333333,   73.66666667,    6.36666667],
        [ 348.33333333,   73.66666667,  150.        ,    9.73333333],
        [  50.        ,    6.36666667,    9.73333333,    5.49333333]]),
 array([[ 314.88888889,  -71.55555556, -180.        ,   14.48888889],
        [ -71.55555556,   32.88888889,    8.        ,   -2.22222222],
        [-180.        ,    8.        ,  168.        ,  -10.4       ],
        [  14.48888889,   -2.22222222,  -10.4       ,    0.73555556]]))

In [ ]:
print(Swg)

[[1286.          220.          348.33333333   50.        ]
 [ 220.           45.33333333   73.66666667    6.36666667]
 [ 348.33333333   73.66666667  150.            9.73333333]
 [  50.            6.36666667    9.73333333    5.49333333]]


In [ ]:
print(Sbg)

[[ 314.88888889  -71.55555556 -180.           14.48888889]
 [ -71.55555556   32.88888889    8.           -2.22222222]
 [-180.            8.          168.          -10.4       ]
 [  14.48888889   -2.22222222  -10.4           0.73555556]]


In [ ]:
# Menghitung S_total
S_total = Sbg + Swg

S_total


array([[ 1.60088889e+03,  1.48444444e+02,  1.68333333e+02,
         6.44888889e+01],
       [ 1.48444444e+02,  7.82222222e+01,  8.16666667e+01,
         4.14444444e+00],
       [ 1.68333333e+02,  8.16666667e+01,  3.18000000e+02,
        -6.66666667e-01],
       [ 6.44888889e+01,  4.14444444e+00, -6.66666667e-01,
         6.22888889e+00]])

In [ ]:
# Menghitung determinan dari Swg dan S_total
det_Swg = np.linalg.det(Swg)
det_S_total = np.linalg.det(S_total)

det_Swg, det_S_total


(866426.091481479, 82701127.84111089)

In [ ]:
# Menghitung Wilks' Lambda
wilks_lambda = det_Swg / det_S_total
wilks_lambda


0.010476593416550445

In [ ]:
# Variabel yang dibutuhkan
p = 4  # jumlah variabel prediktor
k = 3  # jumlah kelompok
N = 9  # total sampel

df_bg = k - 1
df_wg = N - k

# Hitung nilai s dan y
s = min(p, k - 1)
y = np.sqrt(wilks_lambda)

# Hitung df1 dan df2
df1 = p * (k - 1)
df2 = N - k - (p / 2)

# Hitung nilai F
F = ((1 - wilks_lambda) / wilks_lambda) * (df2 / df1)
F

47.22543708817818